name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Scala-Job:
    name: Sbt job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: sbt clean compile
  Sonar-Qube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
     - name: SonarQube Scan
     - uses: kitabisa/sonarqube-action@master
       with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}

      
